### ISSUE TITLE
pwn adventure

### ISSUE THREAD

**Issue by jakhax** [reivhax/News-Highlight#1]
lets play a game

**Comment by jakhax** [comment]
your search macro does not catch errors when the `get_search(keyword)` function does not find an article
`TypeError: 'NoneType' object is not iterable`

**Comment by reivhax** [comment]
Thank you so much, we will be looking into this issue and contact you within 20 or less years.

**Comment by jakhax** [comment]
@reivhax you are not a serious developer (: (:
